# Portfolio Optimization Methods Demo Configuration
# ==================================================
# This configuration demonstrates the three portfolio weight allocation methods:
# 1. equal_weight (1/N Rule)
# 2. top_n (Selective Equal Weight)  
# 3. mean_variance (Markowitz Optimization)
#
# Copy this file and change the portfolio_optimization.method to test different approaches.

experiment:
  name: "portfolio_optimization_demo"
  description: "Demonstrate different portfolio optimization methods"
  tags: ["portfolio", "optimization", "demo"]
  log_to_wandb: false

data_provider:
  type: "YFinanceProvider"
  parameters:
    cache_enabled: true
    max_retries: 3

training_setup:
  model:
    model_type: "xgboost"
    config:
      n_estimators: 50
      max_depth: 4
      learning_rate: 0.1
      random_state: 42

  parameters:
    start_date: "2020-01-01"
    end_date: "2022-12-31"
    symbols:
      - AAPL
      - MSFT
      - GOOGL
      - AMZN
      - NVDA
      - JPM
      - V

# =============================================================================
# PORTFOLIO OPTIMIZATION CONFIGURATION
# =============================================================================
# Uncomment ONE of the following configurations to test:

# Configuration 1: Equal Weight (Recommended for robustness)
portfolio_optimization:
  method: "equal_weight"

# Configuration 2: Top-N (Selective allocation)
# portfolio_optimization:
#   method: "top_n"
#   top_n: 3  # Invest in top 3 assets only

# Configuration 3: Mean-Variance (Traditional optimization)
# portfolio_optimization:
#   method: "mean_variance"
#   risk_aversion: 2.0  # Range: 1-5, higher = more risk-averse

backtest:
  name: "Portfolio_Method_Demo"
  start_date: "2023-01-01"
  end_date: "2023-12-31"
  initial_capital: 100000
  benchmark_symbol: "SPY"
  commission_rate: 0.001
  slippage_rate: 0.0005
  rebalance_frequency: "monthly"
  position_limit: 0.20

strategy:
  type: "ml"
  name: "Demo_Strategy"
  model_id: "placeholder"

