# Prediction Configuration - Meta Model
# =====================================
# Configuration for generating investment predictions from a meta-model ensemble.
# Combines multiple base models with learned weights.

# Prediction settings
prediction:
  prediction_date: "2024-01-15"  # Date to make predictions for
  
# Strategy configuration - use MetaStrategy directly (new architecture)
strategy:
  type: "meta"  # Use the new MetaStrategy type
  name: "Ensemble_Prediction_MetaStrategy"

  # MetaStrategy configuration
  base_model_ids:
    - "ff5_regression_20251015_130842"
    - "xgboost_20251015_010057"

  meta_weights:
    ff5_regression_20251015_130842: 0.60
    xgboost_20251015_010057: 0.40

  # Standard strategy parameters
  min_signal_strength: 0.00001
  enable_normalization: true
  normalization_method: "minmax"
  enable_short_selling: false
  model_registry_path: "./models/"

# Data configuration - same as single model
data_provider:
  type: "YFinanceProvider"
  parameters:
    max_retries: 3
    retry_delay: 1.0

# Factor data provider (required for FF5 base models)
factor_data_provider:
  type: "FF5DataProvider"
  parameters:
    data_frequency: "daily"

# Universe configuration
universe:
  symbols:
    - AAPL
    - MSFT
    - GOOGL
    - AMZN
    - META
    - TSLA
    - NVDA
    - JPM
    - V
    - WMT
    - JNJ
    - PG
    - UNH
    - HD
    - MA
    - DIS
    - PYPL
    - ADBE
    - CRM
    - NFLX

# Portfolio construction - USE FACTORY PATTERN
portfolio_construction:
  method: "box_based"  # Factory determines which builder
  
  # Box-based configuration (same as single model)
  stocks_per_box: 3
  min_stocks_per_box: 1
  allocation_method: "equal"
  allocation_config: {}
  
  # Box weight configuration
  box_weights:
    method: "equal"
    # Only generate boxes for common dimensions that can actually be filled
    dimensions:
      size: ["large", "mid"]  # Remove small caps for minimal test
      style: ["growth"]       # Only growth for simplicity
      region: ["developed"]   # Only developed markets
      sector: ["Technology", "Financial Services", "Healthcare", "Consumer Discretionary", "Consumer Staples", "Communication Services"]  # Match classifier output
      
  # Stock classifier configuration
  classifier:
    method: "four_factor"
    size_breakpoints: [10000, 50000]  # Market cap in millions
    style_method: "pb_ratio"
    cache_enabled: true
    
  # Box selector configuration
  box_selector:
    type: "signal_based"

# Risk constraints
constraints:
  max_position_weight: 0.15
  min_position_weight: 0.02
  max_leverage: 1.0
  max_portfolio_risk: 0.20
  sector_diversification: true

# Output configuration
output:
  format: "detailed"
  include_risk_analysis: true
  include_sector_analysis: true
  include_box_analysis: true
  include_meta_analysis: true  # Show base model contributions
  save_results: true
  output_path: "./prediction_results/"

