# LSTM Strategy Configuration
# ==========================
# This configuration demonstrates LSTM neural network strategy setup with feature engineering.

# Part 1: Data Provider Configuration
# ---------------------------------
data_provider:
  type: "YFinanceProvider"
  parameters:
    max_retries: 3
    retry_delay: 1.0

# Part 2: Training Pipeline Configuration
# ------------------------------------
training_setup:
  model:
    model_type: "lstm"  # Use LSTM model for neural network-based strategy
    config:
      # LSTM architecture parameters - simplified for memory efficiency
      sequence_length: 10      # Reduced number of time steps to look back
      hidden_size: 32          # Reduced number of hidden units
      num_layers: 1            # Single LSTM layer to reduce complexity
      dropout: 0.1             # Lower dropout rate
      bidirectional: false     # Keep unidirectional for efficiency

      # Training parameters - simplified
      learning_rate: 0.01      # Higher learning rate for faster convergence
      batch_size: 16           # Smaller batch size to reduce memory usage
      epochs: 20               # Reduced number of epochs for quick test
      early_stopping_patience: 5   # Reduced patience

      # Device configuration
      device: "cpu"            # Force CPU to avoid GPU memory issues

  feature_engineering:
    enabled_features: ['momentum', 'volatility']  # Reduced feature set
    momentum_periods: [21]        # Single momentum period
    volatility_windows: [20]      # Single volatility window
    lookback_periods: [20]        # Single lookback period
    min_ic_threshold: 0.02
    min_significance: 0.1
    feature_lag: 1
    include_technical: false      # Disable complex technical indicators

  # Parameters for the training pipeline execution
  parameters:
    start_date: "2018-01-01"
    end_date: "2019-12-31"
    symbols:
      - AAPL
      - MSFT
      - GOOGL
      - AMZN
      - META
      - TSLA
      - NVDA
      - JPM
      - V
      - WMT

# Part 3: Strategy Configuration
# ------------------------------
strategy:
  type: ml
  name: LSTMStrategy_v1

  # Model configuration
  model_id: placeholder_model_id  # Will be overwritten by orchestrator
  min_signal_strength: 0.1       # Minimum signal strength threshold

# Part 4: Backtesting Configuration
# --------------------------------
backtest:
  name: "LSTM_Strategy_Backtest"
  start_date: "2020-01-01"
  end_date: "2023-12-31"
  initial_capital: 1000000
  benchmark_symbol: "SPY"
  commission_rate: 0.001
  slippage_rate: 0.0005
  rebalance_frequency: "weekly"
  position_limit: 0.10
  rebalance_threshold: 0.001  # Allow small trades

# Universe configuration
universe:
  - AAPL
  - MSFT
  - GOOGL
  - AMZN
  - META
  - TSLA
  - NVDA
  - JPM
  - V
  - WMT

# Model training (if needed)
model_training:
  train_start: "2018-01-01"
  train_end: "2019-12-31"
  validation_split: 0.2
  test_size: 0.1

# Investment Framework for Box-based classification and allocation
investment_framework:
  enabled: false  # Disable box framework for ML strategy

# Experiment tracking configuration
experiment:
  name: "LSTM_Strategy_Experiment"
  project: "bloomberg-competition"
  tags: ["lstm", "neural_network", "ml_strategy"]
  notes: "LSTM neural network strategy with technical indicators and feature engineering"