# Machine Learning Strategy Configuration Example

# Backtest Configuration
backtest:
  name: "ml_backtest"
  initial_capital: 1000000
  start_date: "2023-01-01"
  end_date: "2023-12-31"
  symbols: ["AAPL", "MSFT", "GOOGL", "AMZN", "META", "TSLA", "NVDA", "JPM", "JNJ", "V"]
  benchmark_symbol: "SPY"

  # Transaction costs
  commission_rate: 0.001
  spread_rate: 0.0005
  slippage_rate: 0.0002
  short_borrow_rate: 0.02

  # Trading parameters
  rebalance_frequency: "weekly"
  position_limit: 0.08
  rebalance_threshold: 0.02

  # Risk management
  max_drawdown_limit: 0.25
  volatility_limit: 0.35
  enable_stop_loss: true
  stop_loss_threshold: -0.08

  # Performance calculation
  risk_free_rate: 0.02

  # Advanced options
  enable_short_selling: true
  enable_leverage: false
  max_leverage: 1.0

  # Output and logging
  save_results: true
  output_directory: "results"
  log_level: "INFO"

# ML Strategy Configuration
strategy:
  name: "ml_residual_strategy"
  strategy_type: "ml"
  universe: ["AAPL", "MSFT", "GOOGL", "AMZN", "META", "TSLA", "NVDA", "JPM", "JNJ", "V"]
  lookback_period: 504

  # Signal generation
  signal_threshold: 0.3
  enable_short_signals: true

  # Position sizing
  allocation_method: "volatility_scaled"
  max_positions: 15
  min_position_weight: 0.02

  # Risk management
  stop_loss_enabled: true
  stop_loss_threshold: -0.08
  position_size_limit: 0.12

  # ML-specific parameters
  parameters:
    # --- Model Versioning ---
    # This ID must correspond to a model saved in the ModelRegistry.
    # It's generated during the training pipeline run.
    model_id: "xgboost_model_20250930_120000" 

    # --- Signal Generation & Portfolio Construction ---
    # These parameters control how raw prediction scores are converted into portfolio weights.
    top_n_assets: 10
    min_prediction_score: 0.05
    max_position_size: 0.15

    # Note: All training, feature engineering, and validation parameters have been removed
    # from this section. That logic is now encapsulated in the TrainingPipeline and
    # the artifacts (model + feature_pipeline) that are loaded via the `model_id`.

# System Configuration
system:
  name: "ml_system"
  core_weight: 0.60
  satellite_weight: 0.40
  max_positions: 25
  rebalance_frequency: 7
  risk_budget: 0.18
  volatility_target: 0.15

  # Advanced parameters
  min_correlation_threshold: 0.6
  max_sector_allocation: 0.20
  ips_compliance_required: true

  # Backtest parameters
  start_date: "2023-01-01"
  end_date: "2023-12-31"
  initial_capital: 1000000
  transaction_costs: 0.0012
  slippage: 0.0006

  # System constraints
  max_leverage: 1.2
  enable_short_selling: true
  emergency_stop_loss: -0.15

  # Monitoring and reporting
  enable_monitoring: true
  monitoring_frequency: "daily"
  report_frequency: "weekly"

  # Strategy orchestration
  strategy_allocation_method: "dynamic"
  enable_strategy_rotation: true
  rotation_frequency: 60

  # Risk management overrides
  override_strategy_risk_params: true
  systemwide_position_limit: 0.08

  # Sector limits
  systemwide_sector_limits:
    Technology: 0.35
    Healthcare: 0.15
    Finance: 0.15
    Consumer: 0.20
    Industrial: 0.10
    Other: 0.05