# Multi-Model Quick Test Configuration
# ====================================
# 快速测试配置：使用较少股票和较短时间周期来验证整个多模型流程

experiment:
  name: "multi_model_quick_test"
  output_dir: "./results/multi_model_quick_test"

# Data configuration (shared across all models)
data_provider:
  type: YFinanceProvider
  parameters:
    max_retries: 3
    retry_delay: 1.0
    request_timeout: 30
    cache_enabled: true

factor_data_provider:
  type: FF5DataProvider
  parameters:
    data_frequency: "daily"
    cache_enabled: true

# 使用较少的股票进行快速测试
universe:
  - AAPL  # Apple
  - MSFT  # Microsoft
  - GOOGL # Google
  - META  # Meta
  - NVDA  # NVIDIA

# 使用较短的时间周期进行快速测试
periods:
  train:
    start: "2023-01-01"
    end: "2023-06-30"
  test:
    start: "2023-07-01"
    end: "2023-09-30"

# Base models: xgboost 和 ff5_regression
base_models:
  - model_type: "xgboost"
    hpo_trials: 5  # 快速测试使用较少试验次数
    hpo_metric: "sharpe_ratio"
    
  - model_type: "ff5_regression"
    hpo_trials: 3  # 快速测试使用较少试验次数
    hpo_metric: "sharpe_ratio"

# MetaModel: 使用 ridge 方法
metamodel:
  hpo_trials: 5  # 快速测试使用较少试验次数
  hpo_metric: "sharpe_ratio"
  methods_to_try: ["ridge"]  # 只测试 ridge 方法

# Strategy/Backtest configuration (shared)
backtest:
  initial_capital: 1000000
  commission: 0.001
  slippage: 0.0005

strategy:
  type: "MLStrategy"
  parameters:
    signal_threshold: 0.1
    max_positions: 5  # 减少最大持仓数量

# Portfolio construction: 使用 box_based 方法
portfolio_construction:
  method: "box_based"
  rebalance_frequency: "weekly"
  max_positions: 5  # 减少最大持仓数量
  min_position_weight: 0.1
  max_position_weight: 0.3

# 放宽系统要求以便快速测试
system_requirements:
  min_sharpe_ratio: 0.1  # 放宽要求
  max_drawdown_threshold: -0.5  # 放宽要求
  min_win_rate: 0.3  # 放宽要求

# Logging configuration
logging:
  level: "INFO"
  log_to_file: true
  log_file: "./results/multi_model_quick_test/experiment.log"
  log_to_console: true

# Advanced configuration
advanced:
  # 不使用并行处理以避免复杂性
  parallel_processing: false
  max_workers: 1
  
  # Error handling
  error_handling:
    continue_on_model_failure: true
    continue_on_metamodel_failure: false
    max_retry_attempts: 2
    retry_delay_seconds: 3
  
  # Validation
  validation:
    validate_data_quality: true
    validate_model_performance: true
    validate_metamodel_weights: true
    validate_system_requirements: true
