# Portfolio Construction Configuration
# =====================================
# This file demonstrates the configuration for both quantitative and box-based
# portfolio construction methods that can be used with the ModernSystemOrchestrator

# System-level configuration
system:
  initial_capital: 1000000
  enable_short_selling: false

# Portfolio construction configuration
portfolio_construction:
  # Method: "quantitative" or "box_based"
  method: "box_based"  # Change this to "quantitative" for traditional optimization

  # Common configuration
  classifier:
    method: "four_factor"
    cache_enabled: true

  # Method-specific configurations below

  # --- Box-Based Configuration (used when method = "box_based") ---
  box_weights:
    method: "equal"  # "equal" or "config"
    dimensions:
      size: ["large", "mid", "small"]
      style: ["growth", "value"]
      region: ["developed", "emerging"]
      sector: ["Technology", "Financials", "Healthcare", "Consumer Discretionary",
               "Consumer Staples", "Industrials", "Energy", "Utilities",
               "Real Estate", "Materials", "Communication Services"]

  stocks_per_box: 3
  min_stocks_per_box: 1
  allocation_method: "equal"  # "equal", "signal_proportional", or "optimized"
  allocation_config: {}

  # --- Quantitative Configuration (used when method = "quantitative") ---
  universe_size: 100
  enable_short_selling: false

  optimizer:
    method: "mean_variance"  # "mean_variance", "risk_parity", "equal_weight"
    risk_aversion: 2.0

  covariance:
    lookback_days: 252
    method: "ledoit_wolf"

  # Optional box limits for quantitative method
  box_limits:
    size: 0.3
    style: 0.3
    region: 0.4
    # sector limits are optional

  # Optional box-aware sampling for quantitative method
  use_box_sampling: false
  box_sampling:
    stocks_per_box: 5
    sampling_strategy: "top_signals"

  min_history_days: 252

# Strategy configuration
strategies:
  - name: "dual_momentum_core"
    type: "DualMomentumStrategy"
    weight: 0.7
    config:
      lookback_period: 60
      cash_proxy: "SHY"

  - name: "fama_french_satellite"
    type: "FamaFrenchStrategy"
    weight: 0.3
    config:
      lookback_period: 252
      top_n: 20

# Meta-model configuration
meta_model:
  method: "weighted_average"
  config:
    normalize_weights: true

# Compliance configuration
compliance:
  max_single_position_weight: 0.10
  box_exposure_limits:
    size: 0.4
    style: 0.6
    region: 0.5
    sector: 0.25

# Execution configuration
execution:
  max_order_size_percent: 0.05
  commission_rate: 0.001
  max_positions_per_day: 20

# Reporting configuration
reporting:
  daily_reports: true
  save_to_file: true
  output_directory: "reports"
  include_box_analysis: true  # Include box coverage analysis in reports