# Dual Momentum Strategy Configuration
# =====================================
# This configuration demonstrates how to set up a dual momentum strategy
# using the new dependency injection architecture.

strategy:
  type: dual_momentum
  name: DualMomentum252
  
  # Strategy-specific parameters
  lookback_period: 252      # Momentum lookback period in days
  top_n: 5                  # Number of top performers to select
  min_momentum: 0.0         # Minimum momentum threshold (absolute momentum filter)
  
  # Position sizing and risk management
  position_sizing:
    volatility_target: 0.15      # Target portfolio volatility
    max_position_weight: 0.10    # Maximum weight per position
    
  # Additional parameters
  rebalance_frequency: monthly   # Rebalancing frequency

# Backtest configuration
backtest:
  start_date: "2020-01-01"
  end_date: "2023-12-31"
  initial_capital: 1000000
  
  # Transaction costs
  costs:
    commission: 0.001           # 0.1% commission
    slippage: 0.0005           # 0.05% slippage

# Universe configuration
universe:
  - AAPL
  - MSFT
  - GOOGL
  - AMZN
  - META
  - TSLA
  - NVDA
  - JPM
  - V
  - WMT

