# LSTM Strategy Configuration (Debug Version)
# ========================================
# Simplified configuration for debugging segfault issues

# Part 1: Data Provider Configuration
# ---------------------------------
data_provider:
  type: "YFinanceProvider"
  parameters:
    max_retries: 3
    retry_delay: 1.0

# Part 2: Training Pipeline Configuration
# ------------------------------------
training_setup:
  model:
    model_type: "lstm"
    config:
      # LSTM architecture parameters - reduced for debugging
      sequence_length: 5        # Reduced sequence length
      hidden_size: 16           # Reduced hidden size
      num_layers: 1             # Single layer
      dropout: 0.0              # No dropout for stability
      bidirectional: false     # Keep unidirectional

      # Training parameters - simplified
      learning_rate: 0.01
      batch_size: 8             # Smaller batch size
      epochs: 2                 # Very few epochs for debugging
      early_stopping_patience: 1

      # Device configuration
      device: "cpu"            # Force CPU to avoid GPU issues

  feature_engineering:
    enabled_features: ['momentum']  # Reduced feature set
    momentum_periods: [10]          # Single momentum period
    volatility_windows: [10]        # Single volatility window
    lookback_periods: [10]          # Single lookback period
    min_ic_threshold: 0.02
    min_significance: 0.1
    feature_lag: 1
    include_technical: true

  # Parameters for the training pipeline execution
  parameters:
    start_date: "2018-06-01"    # Shorter time period
    end_date: "2018-12-31"
    symbols:
      - AAPL
      - MSFT
      - GOOGL    # Reduced symbol count

  # Disable hyperparameter optimization for debugging
  hyperparameter_optimization:
    enabled: false

# Part 3: Strategy Configuration
# ------------------------------
strategy:
  type: ml
  name: LSTMStrategy_Debug
  model_id: placeholder_model_id
  min_signal_strength: 0.1

# Disable other complex features
hyperparameter_optimization:
  enabled: false

# Part 4: Backtesting Configuration (simplified)
# --------------------------------
backtest:
  name: "LSTM_Debug_Backtest"
  start_date: "2019-01-01"
  end_date: "2019-03-31"     # Shorter backtest period
  initial_capital: 100000
  benchmark_symbol: "SPY"
  commission_rate: 0.001
  slippage_rate: 0.0005
  rebalance_frequency: "weekly"
  position_limit: 0.10
  rebalance_threshold: 0.001

# Universe configuration (reduced)
universe:
  - AAPL
  - MSFT
  - GOOGL

# Model training (simplified)
model_training:
  train_start: "2018-06-01"
  train_end: "2018-12-31"
  validation_split: 0.2
  test_size: 0.1

# Investment Framework for Box-based classification and allocation
investment_framework:
  enabled: false

# Experiment tracking configuration
experiment:
  name: "LSTM_Debug_Experiment"
  project: "bloomberg-competition"
  tags: ["lstm", "debug", "minimal"]
  notes: "Minimal LSTM configuration for debugging segfault issues"